---
application:
  name: "bookdlbot"
  project: "Samfun"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "Bookdlbot"
  version: "4.4"
routers:
- name: "main-bookdlbot"
  routes:
  - application_name: "bookdlbot"
    paths:
    - "/*"
